version: '3'
services:
  postgres:
    image: postgres:latest

  elasticsearch:
    image: elasticsearch:7.4.0
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  portal_server:
     build: .
     ports:
        - "5000:5000"
        - "8081:8081"
