version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  server:
    build: .
    image: s4
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      - ELASTIC_URI=http://elasticsearch:9200/
      - POSTGRES_URI=postgres
    depends_on:
      - elasticsearch
      - postgres
    entrypoint: python ./__main__.py --server

  portal:
    image: s4
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - SERVER_URI=server
    depends_on:
      - server
    entrypoint: python ./__main__.py --portal

volumes:
  esdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/tmp' 
    